"""fix embedding dim to 384

Revision ID: 872ddc03dac0
Revises: 62e57ab07474
Create Date: 2026-06-13 16:41:10.414366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '872ddc03dac0'
down_revision: Union[str, Sequence[str], None] = '62e57ab07474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('embedding', Vector(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'embedding')
    # ### end Alembic commands ###
